### ISSUE TITLE
Link for downloading static library for android and ios shows as suspicious link.

### ISSUE THREAD

**Issue by spsingh559** [hyperledger/aries-mobileagent-xamarin#15]
The download link mentioned in https://github.com/hyperledger/aries-mobileagent-xamarin/tree/master/libs README.md file shown as a fake or suspicious link

![image](https://user-images.githubusercontent.com/20536576/97287867-257af000-1856-11eb-9e4f-e9f9f0309b7f.png)
 
Though we can ignore the warning, it should be better to place or host in a much better way.
 Link: https://hyperledger-org.bintray.com/aries/

**Comment by tmarkovski** [comment]
Could this have been a temporary issue? The link points to the Hyperledger account on Bintray. You shouldn't be getting this warning.
I can't seem to reproduce it.

**Comment by Korushdev** [comment]
This link is not working as bintray has been deprecated. Is there an alternate source for the libraries?
