### ISSUE TITLE
Issue credential

### ISSUE THREAD

**Issue by juvebogdan** [hyperledger/aries-mobileagent-xamarin#24]
I am unable to issue credential. I used faber demo from arise cloud agent and connection goes through. Basic message also works fine but when I try issue credential, on mediator i can see it comes through but FetchInboxAsync call on mobile agent says processedCount 0. How can I debug this further? 

I went line by line in FetchInboxAsync and I am facing this issue:

Hyperledger.Aries.AriesFrameworkException: Couldn't locate a message handler for type did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/2.0/offer-credential

Does this mean this is not implemented in this demo?

**Comment by juvebogdan** [comment]
I changed my issuer agent to use 1.0 endpoints since this demo expects those. Now I can receive the credential but accepting one does not work.

I get the following popup after clicking accept:

An unmapped error with the code '309' was returned by the SDK.

Can I get some help with this?

**Comment by juvebogdan** [comment]
indy folder on mobile device contained wrong genesis URL. Removing folder solved it

**Comment by safwanAhman** [comment]
> indy folder on mobile device contained wrong genesis URL. Removing folder solved it

hello I'm currently facing the same problem. Where is the indy folder located in the mobile device?

**Comment by horationunez** [comment]
@safwanAhman you can change the genesis file in the project. they can be found as text resource files in the iOS and Android projects.

**Comment by safwanAhman** [comment]
> @safwanAhman you can change the genesis file in the project. they can be found as text resource files in the iOS and Android projects.

hello! thanks for this. I've done that but now I'm getting an sdk error 307 on my mobile app. Exception caused by timeout
