### ISSUE TITLE
bintray.com will be deprecated and libraries are unreachable.

### ISSUE THREAD

**Issue by serkankaplan** [hyperledger/aries-mobileagent-xamarin#28]
Static library URL documented in the readme ('https://hyperledger-org.bintray.com/aries/') is unreachable and returns forbidden.

**Comment by serkankaplan** [comment]
Link is working again.

**Comment by rkirandas** [comment]
The issue is still persisting, could you please provide an alternate link for downloading static libraries required for iOS and Android
