### ISSUE TITLE
Mediator Stuck and isn't Updating (sending/receiving messages to mobile agent)

### ISSUE THREAD

**Issue by x0axz** [hyperledger/aries-mobileagent-xamarin#33]
2 Months ago, updated the `Hyperledger.Aries.Routing.Edge` to `1.6.1` from `1.4.0` and last week I noticed that we were getting an error in Presentation Proof, used the older version of agents and were still getting that same error. Noticed, that mediator got stuck and wasn't updating (after every 10 seconds, it route messages to mobile agent from issuer/verifier agent).

Now, using `1.4.0` again and Connections are most of time stuck in Negotiating, Credentials in Requested state e.t.c, and all these issues because of the reason that Mediator stuck and isn't routing messages. 

I only noticed this error in mediator logs few times.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Hyperledger.Aries.AspNetCore.AgentMiddleware.Invoke(HttpContext aHttpContext, IAgentProvider aAgentProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by x0axz** [comment]
@horationunez what I noticed is that, when Issuer sends a credential proposal to mobile or issue credentials to mobile OR verifier asks from mobile to verify the credentials by presenting proof, when Mediator Received the Payload from Issuer/Verifier, mobile stops sending an Agent Message (which mobile sends to mediator after 3 second time interval) to check if mediator has any message for it.

Sometimes after many minutes later, mediator starts receiving messages or I have to restart the mediator.

I never faced this kind of behavior before, I haven't change anything in the code. Is there any thing maybe I'm doing wrong?

**Comment by horationunez** [comment]
You should have a lot of control when it comes to check for new Messages in the Mediator. In this [line](https://github.com/hyperledger/aries-mobileagent-xamarin/blob/7219d7a27ed3c88c80bfa51c4c34893664d585c4/src/Osma.Mobile.App/App.xaml.cs#L148) we explicitly request to check for new messages.

Are you also using the latest possible Mediator package?

If you keep having problems I'm happy to jump on a call to help you debug the problem later this week. 

You can setup a time in this link: https://calendly.com/merthin/ariesmax

**Comment by x0axz** [comment]
Thanks for response, actually we compared the code with older version and didn't found any much differences. Downgrade the packages, still we see the delays.

Thank you for taking the time, could you give us time in tomorrow or the day after tomorrow?

**Comment by horationunez** [comment]
No worries. The day after tomorrow sounds good +1

**Comment by x0axz** [comment]
Thanks. Add a slot in calendar.

**Comment by x0axz** [comment]
Hi @horationunez , I downgrade the `Hyperledger.Aries.Routing.Edge` to `1.2.9` in Mobile app, which is same as in Mediator, and the delay isn't too long now.

I didn't understand why downgrading the aries packages in mobile and mediator, take less time to Establish Connection, Issue Credentials and Verify Credentials, compared to latest aries packages.

**Comment by x0axz** [comment]
Solved the Problem!!!

In `App.xml.cs`, there is a function `OnStart()`, where the mediator timer is set to enabled. What I was doing wrong was, I put the statement (`timer.Enabled = true;`) inside the `else` statement, where It should be enabled no matter which condition become true. 

```
protected override async void OnStart()
{
	if (Preferences.Get(AppConstant.LocalWalletProvisioned, false))
	{    }
	else
	{    }
	
	timer.Enabled = true;
}
```
